USE Dadwal_Motors_Analytics;
GO

INSERT INTO silver.FactSales
(
    SalesID,
    SalesDate,
    CustomerID,
    DealershipID,
    SalespersonID,
    VehicleID,
    SalesChannel,
    PaymentMethod,
    PaymentTermMonths,
    CustomerPurchaseNumber,
    CustomerPurchaseType,
    DaysSincePreviousPurchase,
    PurchaseIntervalBand,
    CustomerTenureMonths,
    CustomerTenureBand,
    Quantity,
    MSRP,
    ActualCost,
    BaseDiscountRate,
    PromotionAdjustment,
    FinalDiscountRate,
    MarketAdjustmentRate,
    SalePrice,
    Revenue,
    GrossProfit,
    GrossMarginRate,
    GrowthFactor,
    SeasonalityFactor,
    MonthStart
)
SELECT
    NULLIF(LTRIM(RTRIM(SalesID)), ''),
    TRY_CONVERT(DATE, SalesDate),
    NULLIF(LTRIM(RTRIM(CustomerID)), ''),
    NULLIF(LTRIM(RTRIM(DealershipID)), ''),
    NULLIF(LTRIM(RTRIM(SalespersonID)), ''),
    NULLIF(LTRIM(RTRIM(VehicleID)), ''),
    NULLIF(LTRIM(RTRIM(SalesChannel)), ''),
    NULLIF(LTRIM(RTRIM(PaymentMethod)), ''),
    TRY_CONVERT(INT, PaymentTermMonths),
    TRY_CONVERT(INT, CustomerPurchaseNumber),
    NULLIF(LTRIM(RTRIM(CustomerPurchaseType)), ''),
    TRY_CONVERT(INT, TRY_CONVERT(FLOAT, NULLIF(LTRIM(RTRIM(DaysSincePreviousPurchase)), ''))),
    NULLIF(LTRIM(RTRIM(PurchaseIntervalBand)), ''),
    TRY_CONVERT(INT, CustomerTenureMonths),
    NULLIF(LTRIM(RTRIM(CustomerTenureBand)), ''),
    TRY_CONVERT(INT, Quantity),
    TRY_CONVERT(DECIMAL(18,2), MSRP),
    TRY_CONVERT(DECIMAL(18,2), ActualCost),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, BaseDiscountRate)),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, PromotionAdjustment)),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, FinalDiscountRate)),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, MarketAdjustmentRate)),
    TRY_CONVERT(DECIMAL(18,2), SalePrice),
    TRY_CONVERT(DECIMAL(18,2), Revenue),
    TRY_CONVERT(DECIMAL(18,2), GrossProfit),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, GrossMarginRate)),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, GrowthFactor)),
    TRY_CONVERT(DECIMAL(18,12), TRY_CONVERT(FLOAT, SeasonalityFactor)),
    TRY_CONVERT(DATE, MonthStart)
FROM bronze.FactSales;
GO
